FROM --platform=$TARGETPLATFORM quay.io/mmortari/demo20241108-base:latest
WORKDIR /models

COPY model.joblib ./

# only for making sure what this image contains in directory
# works only if FROM busybox, since the bare image does not provide sh/ls
# but worked the Modelcar tutorial with the above WORKDIR /models, COPY model.joblib ./
# RUN ls -la /models
