FROM --platform=$TARGETPLATFORM ghcr.io/tarilabs/odh-modelcar-base-image/my-app:latest
WORKDIR /models

COPY mnist.onnx ./
COPY README.md ./

# does not work with the odh-modelcar-base-image, and left note here 
# use FROM subtsituion when in need of making sure: what this image contains in directory?
# works only if FROM busybox, since the bare image does not provide sh/ls
# but worked the Modelcar tutorial with the above WORKDIR /models, COPY model.joblib ./
# RUN ls -la /models
