name: Build and Publish Image
on:
  push:
    branches:
      - main

env:
    IMAGE_NAME: odh-modelcar-base-image # per RHOAIENG-21902
    IMAGE_TAGS: latest ${{ github.sha }}
    IMAGE_REGISTRY: quay.io/mmortari # per RHOAIENG-21902 "quay repo - quay.io/opendatahub/odh-modelcar-base-image" so without "-io"
    # REGISTRY_USER: ${{ github.actor }} was used to push to ghcr.io registry
    # REGISTRY_PASSWORD: ${{ github.token }} was used to push to ghcr.io registry

jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        oci: true # must have OCI format
        archs: amd64, arm64
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        containerfiles: |
          ./Containerfile

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.QUAY_MODELCAR_BOT_USERNAME }} # per RHOAIENG-21902
        password: ${{ secrets.QUAY_MODELCAR_BOT_TOKEN }} # per RHOAIENG-21902
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        # username: ${{ env.REGISTRY_USER }} was used to push to ghcr.io registry
        # password: ${{ env.REGISTRY_PASSWORD }} was used to push to ghcr.io registry

    - name: Echo outputs
      run: |
        echo "${{ toJSON(steps.push.outputs) }}"

    - name: Set up Cosign
      uses: sigstore/cosign-installer@v3
    - name: Cosign Keyless Sign
      run: |
        cosign sign --yes ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
